### ISSUE TITLE
Python From Precompiled Unable To Find DLL Path

### ISSUE THREAD

**Issue by otnj** [jeog/TDAmeritradeAPI#11]
Sorry to bother. Trying to run the API using Python 3.7. Have tried to follow the instructions -- tdma_api sitting in python37/lib (I'm able to inherit the module). When it goes to locate the TDAmeritradeAPI.DLL I get failure "unable to find the dll". I've put the path in via clib.init() and still nothing. 

I've tried putting the DLL in with the tdma_api as well as on my System32..

Can you direct me where I should be putting this DLL? 

Thanks, loved TOSDataBridge!

**Comment by jeog** [comment]
The best approach is to add the location of the DLL (and dependencies) to your PATH ([see install](https://github.com/jeog/TDAmeritradeAPI#windows-2)). 

Alternatively, if you try to load it manually via clib.init() double check you are using the correct path, and if it includes backslashes make sure they are properly escaped.
