### ISSUE TITLE
How can I get detail order information?

### ISSUE THREAD

**Issue by JackFlaa** [jeog/TDAmeritradeAPI#13]
I used to place market order to trade, but I found that there is no method to get the exact price of the filled order, and the OrderGetter class just returns the order_id being used. How can i get the detailed information about a specific order?
![5224c3c9cf825958856ef43aeeb86fe](https://user-images.githubusercontent.com/37711290/73284137-1df0c280-41c2-11ea-90b6-dd5757635b17.png)

**Comment by JackFlaa** [comment]
I tried another way to get the order information, but get key errors for that. Any suggestion for me?
![0b2856ae57494f41ca951d533be72a0](https://user-images.githubusercontent.com/37711290/73399763-d3507280-42b5-11ea-9538-94eb5f059bf7.png)
![61f4be504c834d29ce373c57e754569](https://user-images.githubusercontent.com/37711290/73399766-d51a3600-42b5-11ea-807b-18097508b31f.png)

**Comment by jeog** [comment]
The .get() method of the OrderGetter object should return a python object with a bunch of information about the order(assuming you use the correct account and order id). I don't remember the exact structure but in your code example if you do `print(j)` it should display the whole thing.

Future questions like this can be answered by reading the README files or looking at tdameritrade's api site (https://developer.tdameritrade.com/apis).

**Comment by JackFlaa** [comment]
Thanks! Problem solved by just using print(j).
