### ISSUE TITLE
How to test with Paper account?

### ISSUE THREAD

**Issue by bnemetchek** [jeog/TDAmeritradeAPI#16]
I have credentials to a live TD Ameritrade account, but don't want to test with real $.  How do you determine/specify the paper account?

**Comment by jeog** [comment]
As far as I know TDMA doesn't allow API access for a paper account. They said they were going to setup a sandbox for testing but  I haven't seen anything.

**Comment by RcFlyer1201** [comment]
What I have done is do that type of testing on the weekend, before or after hours so I could cancel the orders.

**Comment by dizengoff** [comment]
Hey everyone, I’m new to the list.

Depending on your strategy the issue I can foresee is that paper trade and
live have differences. We’re currently working through a credit spread
strategy that tests wonderfully on the historical data side, but we have
difficulty getting filled on the live side.

**Comment by bnemetchek** [comment]
Thank you to those who answered.  It's disappointing that it's currently not possible to test with a paper account but at least I have a definitive answer.  It makes me a little curious if the ThinkOrSwim platform uses the same API?  If so, perhaps the network traffic could be monitored to see what they're doing though I suspect it's a different API.  

As to the question about how to get orders filled, I'm new to this, but I would expect that there are techniques that trading algo's could use to expedite getting orders filled.

**Comment by dizengoff** [comment]
Yes, they use speed of execution and proximity to the exchange.

Computer and software latency are much higher than dedicated FPGA hardware.
Many of the firms here in town use dedicated, custom designed hardware for
trade execution.

If you’re doing swing trading or anything like that it’s probably not an
issue you need to worry about. We’re doing synthetic credit spreads that
take advantage of short cycle price fluctuations so execution style and
speed are important for us.

**Comment by bnemetchek** [comment]
Thanks again for the good info.  As I'm new to this arena, I sense that there is a whole world of info that I will need to research before I can safely proceed.  Is anyone aware of a useful forum(s) or some type of info repository that may answer a lot of the typical questions someone new would be asking?

thanks!

**Comment by dizengoff** [comment]
I learned what I know because I’m friends with a number of traders at CBOE,
and my neighbor runs a huge MM that has a HFT arm.

Aside from that, those guys don’t talk about their strategy. It’s far too
competitive of a market.

**Comment by jeog** [comment]
If speed is a critical factor in your strategy using a retail broker's API is not ideal. There are a number of Broker/Dealers that specialize in that type of business, providing different routing strategies to exchanges, dark pools etc. from co-located systems. But, most small traders who are getting into automated/quant trading don't need to worry about any of that - just work on your strategy.

As for paper vs real world trading - it's always going to be a bigger issue w/ option spreads because its much harder to simulate the liquidity profile of multiple option book(s).

**Comment by dizengoff** [comment]
Definitely concur 100%.
