### ISSUE TITLE
Issue getting options data for index

### ISSUE THREAD

**Issue by gregasmaximus** [jeog/TDAmeritradeAPI#17]
I always get a failure back from the API (using OptionChainGetter()), when I use 'SPX' or '^SPX' as the symbol. Perhaps there is a different symbol, but I could not find it in their minimal API documentation. 

Sorry to submit an issue for this little thing, but I'm at a dead end. I also thought that others might know or like to know the answer. So if you are reading this and know the answer, please comment!

**Comment by dizengoff** [comment]
I thought TDA uses $SPX.X?  I could be wrong

**Comment by gregasmaximus** [comment]
You are correct, sir! Thank you. I would not have guessed. I also tried $NDX.X and $RUT.X and $VIX.X; all three work. So I guess the formula is prepend '$' and append '.X'.
