### ISSUE TITLE
credential_builder.py Throws Unable to connect to Mojo BudgetService

### ISSUE THREAD

**Issue by Morssel** [jeog/TDAmeritradeAPI#18]
#### First off I'd like to thank you for putting so much time into this project, so people like myself can have a head start when trying to learn more about Ameritrade Api trading.

I am on a Mac Mojave operating system and have followed the setup instructions to the best of my ability. 

After several hours of attempting to troubleshoot this error, I'd like to bring it to your attention.

Upon running "python3 credential_builder.py myConsumerKey@AMER.OAUTHAP path/to/folder password"

The webpage pops up, after logging in with username/password, and passing the security prompt, and choosing accept when "allow access" is prompted, the page closes. The output in the terminal is: 

```
+ Successfully loaded: /Users/cph/devProjs/TDAmeritradeAPI/Release2/libTDAmeritradeAPI.so
+ Last Build: Mar 19 2020 - 23:24:49
 + Extract Args...
 + Confirm password: password
 + File already exists, overwrite? (yes/no): yes
   Library Path: N/A
   Redirect URI: https://127.0.0.1
   Client ID: myConsumerKey@AMER.OAUTHAP
   Credential Path: path/to/folder
   Credential Password: pa******
```
```
DevTools listening on ws://127.0.0.1:60263/devtools/browser/c93407af-3d3e-4679-bb82-b6fe1b679f3c
[0321/234210.219763:ERROR:BudgetService.cpp(160)] Unable to connect to the Mojo BudgetService.
[0321/234224.405850:ERROR:BudgetService.cpp(160)] Unable to connect to the Mojo BudgetService.
[0321/234239.387430:ERROR:BudgetService.cpp(160)] Unable to connect to the Mojo BudgetService.
[0321/234241.898715:ERROR:BudgetService.cpp(160)] Unable to connect to the Mojo BudgetService.
[0321/234247.726107:ERROR:BudgetService.cpp(160)] Unable to connect to the Mojo BudgetService.
```

#### Are you familiar with this ```Unable to connect to the Mojo BudgetService``` error and a workaround?

I tried a little print debugging and this is what I got:
```
def get_access_code_from_web_interface(client_id, redirect_uri ):
    addr = BASE_AUTH_URL + "&redirect_uri=" +  quote(redirect_uri) \
                + "&client_id=" + quote(client_id)
    old_hook = sys.excepthook
    sys.excepthook = cef.ExceptHook
    cef.Initialize()
    browser = cef.CreateBrowserSync(url=addr, window_title=WINDOW_TITLE)
    print("get_access_code check in 1")
    handler = RequestHandler(redirect_uri)
    print("get_access_code check in 2")
    browser.SetClientHandler(handler)
    print("get_access_code check in 3")
    cef.MessageLoop()
    print("get_access_code check in 4")
    cef.Shutdown()
    print("get_access_code check in 5")
    sys.excepthook = old_hook
    print("get_access_code check in 6")
    if not handler.code:
        raise AccessCodeException("failed to receive access code: " + handler.error)
    print("get_access_code check in 7 and handler..code " + handler.code)
    return handler.code
```

Output:

```
DevTools listening on ws://127.0.0.1:59103/devtools/browser/fc948e1a-1099-4ff6-b900-336af3a1e0b6
get_access_code check in 1
get_access_code check in 2
get_access_code check in 3
[0322/000526.801349:ERROR:BudgetService.cpp(160)] Unable to connect to the Mojo BudgetService.
[0322/000542.650016:ERROR:BudgetService.cpp(160)] Unable to connect to the Mojo BudgetService.
[0322/000544.922826:ERROR:BudgetService.cpp(160)] Unable to connect to the Mojo BudgetService.
[0322/000551.066658:ERROR:BudgetService.cpp(160)] Unable to connect to the Mojo BudgetService.
```

**Comment by jeog** [comment]
That's coming from the cefpython3 library. I've noticed similar error messages in the past but the operation still completes. If you continue with the process do you get a credentials file? I believe the 'path/to/folder' should be the full path e.g path/to/folder/mycreds.creds and once you're done w/ the web interface that file should exist.

**Comment by Morssel** [comment]
Sorry, to be more clear my 'path/to/folder' looks like this ```/Users/myMac/devProjs/TDAmeritradeAPI/secureCredentials/myCredentials.creds``` 

There is a new file (empty?) created with zero bytes at that location.

But according to the print lines (print lines as in the original post) I am using inside the ```get_access_code_from_web_interface``` function the lines:
```cef.MessageLoop()``` 
```cef.shutdown```
```sys.exceptionhook = old_hook``` 
and ```return handler.code```  are not being run.

When I put a print in for the return of ```get_access_code_from_web_interface``` being called in ```main()``` it never prints, like the function never finishes:

```print("in credential_builder main calling get code from web - - - - - - # # ## #")``` This prints
```code = get_access_code_from_web_interface(client_id, redirect_uri)```
```print("in credential_builder main code from web is: " + code)``` This does not print

It would seem to me that everything is hanging once it gets to cef.MessageLoop() and no further code is run. 

I am new to the project so I may be missing something obvious, I really hope you can point out whatever it is I am doing wrong.

**Comment by jeog** [comment]
Can you open the generated .creds file in a text editor and make sure it's completely empty. If so, do you see any other output to stdout/stderr after the 'ERROR BudgetService.cpp' lines when you run it? 

A couple other things to check: that the redirect URI and the consumer key match exactly what you used when you setup the developer account. For example, using http and not https for the redirect uri will cause an issue.
