### ISSUE TITLE
Thank you, stay safe and question.

### ISSUE THREAD

**Issue by VEnvirons** [jeog/TDAmeritradeAPI#20]
Hi Jeog,

Thank you very much for all this hard work.  I hope you are well and staying safe in NYC.

I am running VS 2019 in a windows environment, I downloaded the zip and tried to build solution and got the many warnings like mentioned but also 2 build errors...

LNK1104 cannot open file "libcurl_debug.lib
LNK1104 cannot open file "TDAmeritradeAPI.lib

Any advise would be appreciated to get this to build.  A Youtube video on how to setup the solution, get it to build and perhaps an example on how to make calls would be a dream, and of course I could pay you for your time.

On a side note, I wish you and yours well, as well as all New Yorker's during these very difficult times.  Praying for everyone.

Best,
Sean
Boston

**Comment by jeog** [comment]
Make sure you are doing a 'Release' build (the debug dependencies e.g. libcurl_debug.lib are not included.) 

Build -> Configuration Manager -> Active solution configuration dropdown (top left) -> Release

From there you can also change the 'Active solution platform' to x64.

You'll still see a lot of warnings: most of those are from 3rd party code and shouldn't be an issue. Let me know if that works and I'll update the docs or the solution defaults. If not, please post the exact error messages you see.

**Comment by VEnvirons** [comment]
Ok,
Thanks Jeog I will give it a go.  Thanks and be well.
-S

**Comment by VEnvirons** [comment]
So I got 47 errors afterwards, until I targeted C++ v17 for both projects.  Then there is just 1 error currently here...
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "for /R C:\Users\Sean\Documents\Visual Studio 2019\Projects\TDAmeritradeAPI-master\TDAmeritradeAPI-master\vsbuild\deps\libs\x64\Release %%f in (*.dll *.exe) do copy %%f C:\Users\Sean\Documents\Visual Studio 2019\Projects\TDAmeritradeAPI-master\TDAmeritradeAPI-master\vsbuild\x64\Release
:VCEnd" exited with code 255.	TDAmeritradeAPI	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	149	


which corresponds to...

`<Target Name="PostBuildEvent" Condition="'$(PostBuildEventUseInBuild)'!='false'">
    <Message Text="%(PostBuildEvent.Message)" Condition="'%(PostBuildEvent.Message)' != '' and '%(PostBuildEvent.Command)' != ''" Importance="High" />
    <Exec Command="%(PostBuildEvent.Command)$(_BuildSuffix)" Condition="'%(PostBuildEvent.Command)' != ''"/>
  </Target>`

If you get a chance let me know your thoughts.
Best,
-Sean

**Comment by jeog** [comment]
I believe the problem is the solution path has a space('Visual Studio 2019"). So You can move the project into a different location with no spaces OR

1) right-click TDAmeritradeAPI project -> properties
2) Configuration drop-down -> All Configurations
3) Platform drop-down -> All Platforms
4) Build Events -> Post-Build Event
5) there will be a bold line of text next to 'Command Line' that you should change to(note the new quotation marks):
`for /R "$(SolutionDir)deps\libs\$(Platform)\$(Configuration)" %%f in (*.dll *.exe) do copy "%%f" "$(SolutionDir)$(Platform)\$(Configuration)"`
6) click 'Apply'

**Comment by VEnvirons** [comment]
Worked Jeog!  Thanks, you are awesome!

-S

**Comment by jeog** [comment]
No problem, I just pushed commit ffe64b7557a2939736ba8962f43ebcdf2977653a that will hopefully fix these issues going forward.
