### ISSUE TITLE
TIMESALE_OPTIONS

### ISSUE THREAD

**Issue by perdpg** [jeog/TDAmeritradeAPI#21]
Hi, Jeog,

Great work! I am testing your code. Most of them is working for me. But I couldn't make TIMESALE_OPTIONS work. 

My understanding is that it takes a stock/index symbol, and returns the timesale for all the options (all expiration and all strikes).  Below is the log. It shows that the command succeeded, but no data is returned.

Thanks,
perdpg

"command":"SUBS","parameters":{"fields":"0,1,2,3,4","keys":"SPY"},"requestid":"2","service":"TIMESALE_OPTIONS","source":"zhongg01"}]}

message: {"response":[{"service":"TIMESALE_OPTIONS","requestid":"2","command":"SUBS","timestamp":1586807713685,"content":{"code":0,"msg":"SUBS command succeeded"}}]}

**Comment by jeog** [comment]
I believe it takes the actual option symbols you want T&S for. The fact they return a succeeded message makes it a bit confusing. Try using specific option symbols for some liquid contracts and see if it works.

**Comment by perdpg** [comment]
If it takes the actual option symbol, then what's the difference between TIMESALE_OPTIONS and OptionsSubscription? 

I tried it with SPX/SPY options symbols, same behavor. Commands succeeded but no results returned.

**Comment by jeog** [comment]
The latter is a quote (snapshot) for an option, the former is each executed trade - less fields but more granular. Similar to the difference between QuotesSubscription and TimesaleEquitySubscription.

I took a look at some of the old tests and this symbol worked: SPY_081718C276 - so make sure its in that format (obviously you'll need one that hasn't expired.) Also, in certain cases you need certain fields(not sure why) so for testing be sure to use all fields: SYMBOL, TIME, PRICE, SIZE, SEQUENCE (0,1,2,3,4)

**Comment by perdpg** [comment]
Today I tried TIMESALE_OPTIONS with SPXW_041520C2850 and fields (0,1,2,3,4), and it didn't work either. OptionsSubscription is working. I'll check with  TDA help. Thanks.

"command":"SUBS","parameters":{"fields":"0,1
,2,3,4","keys":"SPXW_041520C2850"},"requestid":"2","service":"TIMESALE_OPTIONS"

{"response":[{"service":"TIMESALE_OPTIONS","requestid":"2","command":"SUBS","timestamp":1586885651783,"content":{"code":0,"msg":"SUBS command succeeded"}}

**Comment by perdpg** [comment]
Got reply from TDA help: "Options Time and Sales is currently disabled on our Streamer API at this time."

**Comment by jeog** [comment]
Ok, thanks for response - I'm sure it will save someone a headache. 

When I get a chance I'll update the docs.
