### ISSUE TITLE
timeout handling

### ISSUE THREAD

**Issue by perdpg** [jeog/TDAmeritradeAPI#22]
From time to time, I got the following timeout error:

CurlConnectionError --> ConnectionException
ABI :: ConnectException --> error code 101
terminate called after throwing an instance of 'tdma::ConnectException'
  what():  curl connection error (28): Operation timed out after 300501 milliseconds with 0 out of 0 bytes received(curl code=28) [error code: 101, file: ../TDA/client/src/tdma_connect.cpp, line: 161]

Should I contact TDA support, or should I add timeout handling (such as re-start the session) in the code?

**Comment by jeog** [comment]
That's coming from one of the Get interface's HTTP/REST connection attempts(its a timeout from the Curl library below it). I believe the only time the streaming session uses the Get interface is immediately on construction to get some account info. Are you doing something via the Get interface alongside the streaming session? Can you provide a little more detail/context on what you're doing when this happens, how often etc?

**Comment by perdpg** [comment]
I was streaming /ES futures_chart and futures_timesale; Also getting option chain every minute.

**Comment by jeog** [comment]
By getting option chains I assume you're using one of the Option Chain Getter objects? If so, that's most likely what's causing the issue.

The timeout can be caused by a number of things. Can you post a sample of the code you're using to get the option chain data. Particularly any code that shows how you are instantiating, moving, storing etc the Option Getter instance(s) and how you are calling its methods.  Also, how often do you notice this happening?

**Comment by perdpg** [comment]
Below is the code. I couldn't make TIMESALE_OPTIONS or ChartOptionsSubscription work. And OptionsSubscription is returning partial data most of the time. So I end up with pulling the chain every minute.

void option_chain_getter(int n)
{
    auto strikes = tdma::OptionStrikes::Range(tdma::OptionRangeType::all);
    tdma::OptionChainGetter ocg(*credentials, "$SPX.X", strikes, tdma::OptionContractType::all, true);

    //if n==0, get only options expiring in current week
    //if n==1, get the whole chain
    if(n==0) ocg.set_to_date(GetOptionToDate());

    json oj = ocg.get();

    //dump the chain to file
    std::ofstream ofs(filename);
    ofs << oj.dump(4) << std::endl;

    for (auto& itd: oj["callExpDateMap"].items() )
        for(auto& its : itd.value().items() )
             for( auto& elemj : its.value() ) {
                //store the chain data
}


int main(int argc, char* argv[]) {
            
    Start();
            
    Add(); //start the streaming 
            
    while() {
        //get the full chain every 5 minutes
        //if not getting the full chain, get current weekly chain every minutue
        if(current_mins > oc0_t && current_mins%5) {
            option_chain_getter(0);
            oc0_t = current_mins;
        }
        if(current_mins > oc1_t && current_mins%5==0) {
            option_chain_getter(1);
            oc1_t = current_mins;
        }
    }

    Stop();

    Finalize();
}

current_mins is updated at:

void
session_callback( int callback_type,
                  int streamer_service_type,
                  unsigned long long time,
                  const char* data )
{

    case StreamingCallbackType::notify:
        {
            string s(data);
            current_mins = stoull(s.substr(s.find("heartbeat")+12))/MSEC_IN_MIN;
            log_error("STREAMING", "notify", (data ? string(data) : "" ) );
            return;
        }


    case StreamerServiceType::CHART_FUTURES:
        for( auto& elemj : j ){
            t = elemj[KF_CHART_TIME];
            current_mins = t / MSEC_IN_MIN;

**Comment by jeog** [comment]
The timeout itself is hard to diagnose (could be a connection issue, some type of issue on the server side, or an issue with the front-end) but some things that may help:

1) Try to avoid constructing/destructing the option Getter on each call. Instantiate it once (global, heap etc.) and pass by pointer or reference. This will limit the number of times the connection is forcefully opened and closed.

2) The default (curl) connect timeout is 5min. If the above doesn't help you can: a) try lowering that timeout with the ::set_timeout method (maybe to 5-10 sec); b) catching the ConnectException when you use the ::get() method; and c) wait a bit and either try ::get() again or destroy the instance and re-instantiate. (Obviously, you won't be able to differentiate the type of connect error - it could be something other than a timeout. There probably should be a timeout exception but the exception/error structure was planned before that timeout was added. A hack would be parsing the exception text in the exception's ::what() method.)

Also, if it's easier you can use multiple getter classes/instances. A while back I setup a [shared backend](https://github.com/jeog/TDAmeritradeAPI/blob/master/README_GET.md#backend) so the different instances will share the same underlying connection.

**Comment by perdpg** [comment]
Thanks a lot!
