### ISSUE TITLE
Running Python Tools

### ISSUE THREAD

**Issue by DaveBGld** [jeog/TDAmeritradeAPI#23]
Impressive work!! Looking forward to experiment with your code. In getting started, I generated the access code at TDAmeritrade, and am trying to generate the credentials, but, when running `creds_from_access_code.py` at line

`from tdma_api import auth, clib
`

I get the error

`ModuleNotFoundError: No module named 'tdma_api'`

Python install seems to have worked well...
```
sudo python3 setup.py install
running install
running build
running build_py
running install_lib
running install_egg_info
Removing /usr/local/lib/python3.6/dist-packages/tdma_api-0.2.egg-info
Writing /usr/local/lib/python3.6/dist-packages/tdma_api-0.2.egg-info
Write build info to: tdma_api_build.info

```

Thanks for you project and any help!!

Dave

**Comment by jeog** [comment]
1) first, just double check you're using the correct command: `python3 creds_from_access_code.py`

2) if so, try opening a python3 shell (from any dir other than TDAmeritradeAPI/python) and let me know if you can import directly: `import tdma_api`

**Comment by DaveBGld** [comment]
Thanks! 

Fixed. It was an issue of virtual environment. When installing w/o activating a virtualenv it worked.

However I got a new problem: both the `creds_from_access_code.py` as well as the C++ function     `RequestAccessToken` return an `invalid_grant` error, and after that I need to delete the developer application at TDAmeritade and create a new one.

I was able to create the first access and refresh tokens at `https://developer.tdameritrade.com/authentication/apis/post/token-0` but using a **URL Decoded** version of the access code. Do these functions need a URL Decoded or just copy paste from the code returned to localhost?

Many thanks,

Dave

**Comment by jeog** [comment]
The script wants a URL-decoded access code by default, but if you use the '--extract-code-from-url' switch you can pass the (entire) raw/encoded url that is returned.

**Comment by DaveBGld** [comment]
Thanks you! I was able to generate the credentials file.

I then proceeded to run tour `cpp` test program and am getting an error:

```
*** [BEGIN] TEST CREDENTIALS [BEGIN] ***
ABI :: LocalCredentialException --> error code 2
```
At the last line of 
`test_credentials(cmanager.credentials);`

On inspecting the credentials object it seems to be all there, and the rest of the test program seems to be working as expected.

Can I contribute a small cosmetic  change in one of your comment lines?
The message line after the line above says [BEGIN] instead of [END]

David

**Comment by jeog** [comment]
Was there any other info provided ? Usually when you get an exception coming out of the library like that you'll get some additional info, and the file name and lineno from where the exception was thrown. 

Are you able to load the credential file on your own and use it for a simple data request, or are you getting a similar error?

**Comment by DaveBGld** [comment]
a) That's all that's displayed with the error
b) The rest of the test program runs so I'm able to connect and the getters and streamers work
c) The error is from this portion of code:

 ```
try{
        Credentials ccc5(
            string(Credentials::CRED_FIELD_MAX_STR_LEN + 1, 'B').c_str(),
            "",0,""
            );
        throw std::runtime_error("failed to throw exception for bad credential field size");
    }catch( LocalCredentialException& e ){
    }
```

**Comment by jeog** [comment]
Ok, that's not really an error. The test is purposely checking the exception is getting thrown and just catching it silently.  Down inside the library there's some exception/error handling stuff that automatically spits out that line whenever an exception is caught at the library boundary and converted to an error code.

**Comment by DaveBGld** [comment]
Solved!!! 

Great Library. Love your coding style. Many Thanks!

Dave
