### ISSUE TITLE
Different periods/frequencies

### ISSUE THREAD

**Issue by DaveBGld** [jeog/TDAmeritradeAPI#24]
Hi Jon!

In my research I need to simultaneously analyse the price action in several intervals as if in looking at a candle chart where each candle is 1 minute, 5 minutes, 15 minutes, and so on... But I see that you have predefined the periods / frequencies used by the getters to 

```
DECL_C_CPP_TDMA_ENUM(PeriodType, 0, 3,
    BUILD_C_CPP_TDMA_ENUM_NAME(PeriodType, day),
    BUILD_C_CPP_TDMA_ENUM_NAME(PeriodType, month),
    BUILD_C_CPP_TDMA_ENUM_NAME(PeriodType, year),
    BUILD_C_CPP_TDMA_ENUM_NAME(PeriodType, ytd)
);

DECL_C_CPP_TDMA_ENUM(FrequencyType, 0, 3,
    BUILD_C_CPP_TDMA_ENUM_NAME(FrequencyType, minute),
    BUILD_C_CPP_TDMA_ENUM_NAME(FrequencyType, daily),
    BUILD_C_CPP_TDMA_ENUM_NAME(FrequencyType, weekly),
    BUILD_C_CPP_TDMA_ENUM_NAME(FrequencyType, monthly)

``` 
I'm guessing that for a 1 minute chart, minute by minute candles I would do:

`    HistoricalRangeGetter hrg(c, "SPY", FrequencyType::minute, 1, start, end, true);
`

And for 15 minute candles I would 

`    HistoricalRangeGetter hrg(c, "SPY", FrequencyType::minute, 15, start, end, true);`

Is this so? If not can you please give me some advise on how to approach this?

A second question, is how do you recommend to handle the last candle with last live data and avoid reloading the whole history.

Many thanks!!

Dave

**Comment by jeog** [comment]
Yes, but keep in mind TDMA restricts you to certain frequency sizes and types.  These relationships are defined in: 

```
const unordered_map<FrequencyType, set<int>, EnumHash<FrequencyType>>
VALID_FREQUENCIES_BY_FREQUENCY_TYPE = {
    {FrequencyType::minute, set<int>{1,5,10,30}},
    {FrequencyType::daily, set<int>{1}},
    {FrequencyType::weekly, set<int>{1}},
    {FrequencyType::monthly, set<int>{1}},
};
```
... so you can do 1-min, 5-min, 10-min, and 30-min candles, but not 15. (If you use the HistoricalPeriodGetter there are other relations defined between 'period' and 'frequency'.)

There's no easy answer to the second question. It really depends on exactly what you're trying to do. One approach is to use the historical requests alongside the streamer and try to sync yourself. (I did [something like this a while back](https://github.com/jeog/TDAmeritradeAPI/tree/master/DynamicDataStore) but, as you can see, it's not the simplest thing. )

**Comment by DaveBGld** [comment]
Thanks Jon!

On the TDAmeritrade developers' API [here](https://developer.tdameritrade.com/price-history/apis/get/marketdata/%7Bsymbol%7D/pricehistory), it says

```
The number of the frequencyType to be included in each candle.

Valid frequencies by frequencyType (defaults marked with an asterisk):

minute: 1*, 5, 10, 15, 30
```
So, what if I change in the above code 
`    {FrequencyType::minute, set<int>{1,5,10,30}},
`

to 
`    {FrequencyType::minute, set<int>{1,5,10,15,30}},
`

Will that suffice? Or is there something else I need to worry about??

Thanks for your super duper great support. I truly appreciate!!

**Comment by jeog** [comment]
Maybe they added it, or I just missed it. If you're using the C++ interface you should be able to redefine it in the header and **recompile the library**. I believe the library implementation is just checking that value exists in that mapping, and throws an exception if it doesn't.

**Comment by DaveBGld** [comment]
Great! Thanks. Your comment from 2 days ago made it so much easier!!

David
