### ISSUE TITLE
Websocket connection stability

### ISSUE THREAD

**Issue by rana** [jeog/TDAmeritradeAPI#26]
Hi Jeog,

Do you encounter websocket connection stability issues with TD Ameritrade? If so, do you mitigate simply by reconnecting to the websocket immediately? 

I've written a client in Julia and Golang and have determined the stability is on TD Ameritrade side. But perhaps you've worked through the issue? Or know some mitigation? Decrease quantity of quote subscriptions? Slow the quality of service? Or, simply re-connect?

Cheers,

Rana

**Comment by RcFlyer1201** [comment]
Rana,

I have had similar issues with TD Ameritrade. It happened last week on more than one occasion. 

I use to assume it was me and try restarting. Then sometimes restarting had problems.

Yesterday there was something that caused it to slow. 

I now just let the program do its thing and so far it has recovered on its own. So far so good.

 

However if the streaming stops, I have always had to restart it. 

 

My programs are  written by me in VB.NET including the TD interface.

 

Bill

**Comment by jeog** [comment]
I haven't used recently so I'm not sure the current quality of connection but in the past I simply had to use some application-layer check and reconnect if necessary. I would try to reconnect N times, and then fail if I couldn't.  I considered adding a more session-level mechanism to the StreamingSession class to manage this but it was already a little clunky and over-written so figured it best to leave to the application. 

So something like this on its own thread:
```
while running:
    if session is not active:
        if already tried to reconnect too many times:
            return error
        try to reconnect
    sleep 
```

**Comment by rana** [comment]
@RcFlyer1201 Yeah, I also thought I was doing something to cause the crashes. Super glad we can share these experiences and find out that it's not us but TD Ameritrade.

@jeog Thanks for the suggestion. Love it, that's just what I'll do. 

I've also tried polling GET `/v1/marketdata/quotes` each second to simulate streaming quotes. The calls are reliable but the data is not. Many of the quotes are _delayed_, making that approach useless. That [quote endpoint documentation](https://developer.tdameritrade.com/quotes/apis) says:
>Request real-time and delayed top level quote data

Well, let me know if you find anything else :+1: 

Cheers :relaxed: 

Rana
