### ISSUE TITLE
Invalid address specified to RtlValidateHeap when attempting to get the JSON result of QuoteGetter

### ISSUE THREAD

**Issue by genisispig** [jeog/TDAmeritradeAPI#28]
My code is the following

```
std::shared_ptr<tdma::CredentialsManager> credMan{ nullptr };
credMan = connections::LoadCredentials( path , password );
tdma::QuoteGetter spyQuote{credMan->credentials, "SPY"};
nlohmann::json result{ spyQuote.get() };
cout << result << endl;
```

Upon running this, I get a `Invalid address specified to RtlValidateHeap` on line 2613 of `tdma_api_get.h`, the `get()` of the `APIGetter` class. This appears to be related to the `free(buf)` on line 2612. 

As `n` = 1059, `json::parse(std::string(buf))` is called and the buffer does contain the proper JSON result with the SPY quote. 

Don't have much experience with c++ or the JSON library used, but `j` contains an string of size 4261281227, which seems a little odd?

My code is based on the example provided in the documentation of the get header file.

Sorry to waste your time if this is something silly in my code that I messed up

**Comment by jeog** [comment]
Looks like it's trying to free a bad address that was not properly assigned deeper in the code.. Can you consistently reproduce this? Does it happen with other Getters?

**Comment by genisispig** [comment]
This is happening every time I tried to use QuoteGetter. I went and tested it with MarketHoursGetter with the same result of Invalid address specified to RtlValidateHeap on every run. As the error is popping up within the base class of APIGetter it seems likely that it will also happen with the other classes.

**Comment by genisispig** [comment]
Welp looks like I didn't follow instructions properly. I was attempting to use the Release version of the library in a Debug build of my own code and didn't realize. Once I switched my build to be a Release version, it worked just fine. Sorry for any time wasted. I do like having debug info, so to build a debug version of the library:

```If you want a debug configuration you'll have to edit the 'Additional Library Directories' in Properties->Linker->General for the TDAmeritradeAPI project so it looks for Release builds of the dependencies. In the path strings change '$(Configuration)' to 'Release\'.*```

Will just changing the path strings for each dependency allow me to build a proper debug build that can be incorporated into a debug build of my project?

**Comment by jeog** [comment]
It should. We don't have debug builds of the dependencies included so you need to link to the release builds. If this causes any issues you would need to compile debug builds of the dependencies and link to those.
