### ISSUE TITLE
auth problem

### ISSUE THREAD

**Issue by gracekk** [jeog/TDAmeritradeAPI#3]
Just now, my function hint me errors as below:

error response: 401
access token expired; try to refresh...
ABI :: LocalCredentialException --> error code 2
ABI :: LocalCredentialException --> error code 2
Traceback (most recent call last):
  File "D:\aaa\TDAmeritradeAPI\test\run.py", line 51, in <module>
    j = getter.get()
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\tdma_api\get.py", line 227, in get
    r = clib.get_str('APIGetter_Get_ABI', self._obj)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\tdma_api\clib.py", line 155, in get_str
    call(fname, REF(obj), REF(c), REF(n))
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\tdma_api\clib.py", line 122, in call
    raise CLibException(err)
tdma_api.clib.CLibException: TDMA_API_CRED_ERROR: refresh token has expired; use RequestAccessToken() for new token [error code: 2, file: c:\users\j\documents\github\tdameritradeapi\src\auth.cpp, line: 707] [error code: 2, line: 707, file: c:\users\j\documents\github\tdameritradeapi\src\auth.cpp]

Then I success get new access_token with https://developer.tdameritrade.com/content/simple-auth-local-apps  steps.

Then I try to store creds like this:

if __name__ == '__main__':
    from tdma_api import get, auth, clib, stream, execute, common
    creds = auth.request_access_token("token", "client_id")
    store_credentials("aaa.txt","bbb",creds)

But get errors as below:
error response: 400
RequestAccessTokenImpl failed: {
  "error" : "invalid_grant"
}

I forgot last successfully store the creds steps,  is the "token" parameter need decode or add "Bearer"?
or  "client_id" just the ID or need add "@AMER.OAUTHAP"?
I'm not sure the problem is TD official or the library.
FYI:  I use the token with TD web api manually get correct response.
Any suggestion?  Thanks.

**Comment by gracekk** [comment]
My own fault,   just solved.
auth.request_access_token("code", "client_id") 
just pass code not token.
Seems the token needs to be updated every 90 days.

**Comment by jeog** [comment]
FWIW, you can manually check the 'epoch_sec_token_expiration' field of the Credentials object, which will indicate the number of seconds-since-the-epoch when the refresh token expires. It's calculated using the System Clock of they system that called 'RequestAccessToken'. Since TDMA doesn't alert you that the refresh token expired the library checks when the current time gets within 1 day of this value and throws an exception.
