### ISSUE TITLE
options with futures

### ISSUE THREAD

**Issue by brw59** [jeog/TDAmeritradeAPI#7]
There doesn't seem to be a way to get options for futures. Is this a TD Ameritrade API limitation?

For instance: /PA is Palladium, and can be traded with options in the thinkorswim tool, but I haven't been able to figure it out with the API yet.

```
    strikes = get.OptionStrikes.N_ATM(2)
    from_date = "2019-04-01"
    to_date = "2019-12-31"
    g = get.OptionChainGetter(creds, "/PA", strikes,
                              get.OPTION_CONTRACT_TYPE_ALL, True,
                              from_date, to_date, get.OPTION_EXP_MONTH_ALL,
                              get.OPTION_TYPE_ALL)
    j = Get(g)
    jprint(j)

```

and this is the result:

```
{
    "symbol": "/PA",
    "status": "FAILED",
    "underlying": null,
    "strategy": "SINGLE",
    "interval": null,
    "isDelayed": false,
    "isIndex": false,
    "interestRate": 0.0,
    "underlyingPrice": 0.0,
    "volatility": 0.0,
    "daysToExpiration": 0.0,
    "callExpDateMap": {},
    "putExpDateMap": {}
}
```

I've also tried various other things that don't seem to work either 'PA', '/PAM', 'PAM', '/PAOM', ...

Is there a way to get future options? or is that just not available?

**Comment by jeog** [comment]
Probably not, but you should confirm w/ TDMA.

You can get L1 info via [streamer](https://github.com/jeog/TDAmeritradeAPI/blob/master/README_STREAMING.md#levelonefuturesoptionssubscription) but that uses the actual option symbol (e.g /ESM9C2900) and not the whole chain.

**Comment by brw59** [comment]
Looks like they don't have it currently scheduled to implement, upon asking when they might have Options with Futures, this was their response:
"Thank you for your email.  Our Get Option Chain restful service is only available for stocks, ETFs, and Indexes.  We hope to add support for futures and futures options in the future, but we do not have an ETA for when that is available."

Thanks for the QuoteGetter and Streamer suggestion.

**Comment by sanjinbecirovic** [comment]
> Probably not, but you should confirm w/ TDMA.
> 
> You can get L1 info via:
> 
> 1. QuoteGetter/[QuotesGetter](https://github.com/jeog/TDAmeritradeAPI/blob/master/README_GET.md#quotesgetter)
> 2. [Streamer/LevelOneFuturesOptionSubcscription](https://github.com/jeog/TDAmeritradeAPI/blob/master/README_STREAMING.md#levelonefuturesoptionssubscription)
> 
> But both are for an individual option symbol (e.g /ESM9C2900) and not the whole chain.

@jeog is this still the only approach to get futures options market data, I have tried, but I guess I dont know the symbol structure as the api always returns empty result.

**Comment by IV2KBMoFxYIA** [comment]
any further progress on this? i can't seem to find any broker with futures options API access.
