### ISSUE TITLE
OptionChainGetter values

### ISSUE THREAD

**Issue by nfischer0** [jeog/TDAmeritradeAPI#8]
The Greeks for options called using the OptionChainGetter objects do not seem to match the values on Thinkorswim.  The difference is not huge, but nonetheless they are different.  I'm not sure if this is a TDA issue or not.  I also do not know where the theoreticalVolatility/volatility fields come from, as they don't belong to the underlying or the option itself.

**Comment by jeog** [comment]
My guess is this is a TDA issue. You can compare the data returned from the Getter w/ the web interface (https://developer.tdameritrade.com/option-chains/apis/get/marketdata/chains) to see if they match. The difference between TOS and the API could be any number of things: data source, timing  etc.

The library doesn't really do anything to the returned json data, so the values you see are most likely what TDA is returning.

**Comment by nfischer0** [comment]
Got it. Thanks!
